export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_PASSOWORD_REQUEST = "UPDATE_PASSOWORDREQUEST";
export const UPDATE_PASSOWORD_SUCCESS = "UPDATE_PASSOWORD_SUCCESS";
export const UPDATE_PASSOWORD_RESET = "UPDATE_PASSOWORD_RESET";
export const UPDATE_PASSOWORD_FAIL = "UPDATE_PASSOWORD_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";

export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
